Repository slaclab/trace, pull requests merged in 2025-09, with the labels that each got.

#187 DOCS: Update Documentation for UI Redesign
  .github/workflows/gh-pages.yml
  .gitignore
  docs-requirements.txt
  docs/api_reference/axis_table.md
  docs/api_reference/plot_config.md
  docs/api_reference/trace.md
  docs/api_reference/traces_table.md
  docs/arguments.md
  docs/how_to/file_conversion.md
  docs/how_to/overview.md
  docs/how_to/traces.md
  docs/images/Trace_Screenshot.png
  docs/images/axis_settings.png
  docs/images/config_section.png
  docs/images/footer.png
  docs/images/formula_maker.png
  docs/images/line_style.png
  docs/images/line_type.png
  docs/images/plot_section.png
  docs/images/search_tool.png
  docs/images/sections.png
  docs/images/sqwave-blwh.svg
  docs/images/trace_settings.png
  docs/images/traces.png
  docs/images/y_axes.png
  docs/index.md
  docs/installation.md
  docs/io.md
  docs/overview.md
  docs/overview/config_section.md
  docs/overview/footer.md
  docs/overview/plot_section.md
  docs/plot_config.md
  docs/reference/file_io/file_handler.md
  docs/reference/file_io/index.md
  docs/reference/file_io/time_parser.md
  docs/reference/file_io/trace_file_convert.md
  docs/reference/index.md
  docs/reference/services/elog_client.md
  docs/reference/services/index.md
  docs/reference/trace.md
  docs/reference/widgets/archive_search.md
  docs/reference/widgets/control_panel.md
  docs/reference/widgets/data_insight_tool.md
  docs/reference/widgets/elog_post_modal.md
  docs/reference/widgets/helper_widgets.md
  docs/reference/widgets/index.md
  docs/reference/widgets/settings_popups.md
  docs/tools/data_insight.md
  docs/tools/elog_entry.md
  docs/tools/file_converter.md
  docs/tools/formula_maker.md
  docs/tools/search.md
  docs/traces.md
  docs/traces_table_menu.md
  docs/y_axes.md
  mkdocs.yml
Labels: documentation, CI/CD

#198 ENH: New Curves Are Added to Axes Based on Units
  trace/stylesheets/dark_mode.qss
  trace/stylesheets/light_mode.qss
  trace/widgets/control_panel.py
Labels: enhancement

#200 FIX: Error with AxisItem.set_active & Curve Artifacts Remaining on Previous Axis
  trace/widgets/control_panel.py
Labels: bug

#201 FIX: Hide Bin Count Setting for FormulaCurves
  trace/widgets/curve_settings.py
Labels: bug
